# Generated by Django 5.2.1 on 2025-06-01 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(choices=[('VID', 'Vidrio'), ('PAP', 'Papel'), ('PLA', 'Plástico'), ('LAT', 'Latas'), ('ORG', 'Orgánico'), ('ELE', 'Electrónicos')], max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_retiro', models.DateField()),
                ('direccion_retiro', models.CharField(max_length=255)),
                ('comentario', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En Ruta'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
