# Generated by Django 5.2.1 on 2025-06-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudretiro',
            name='completado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
